### ISSUE TITLE
Accessing the Google Calendar API requires different authorization

### ISSUE THREAD

**Issue by Shiroraven** [Shiroraven/Jikanri#2]
Firebase provides Google OAuth authentication capabilities, however it does not authorize use of the Google Calendar API.

To fix this users may need to sign in using Google Sign in for Web https://developers.google.com/identity/sign-in/web/sign-in

The acquired JSON Web Token can then be passed to the Google Calendar API client for authorization.

**Comment by DillonSimeone** [comment]
There's no issues with getting access to the google calendar api for users. As you can see in the screenshot below this snippet of code from src/pages/Setup.svelte is updating the scope just fine.

```
...
let provider = new firebase.auth.GoogleAuthProvider();
provider.addScope("https://www.googleapis.com/auth/calendar");
...
```
![image](https://user-images.githubusercontent.com/21962421/77219080-6c01b280-6aef-11ea-9abf-59a117556819.png)

The issue preventing me from accessing the calendar api appears to be related to something Svelte or rollup is doing to the script files.

 In the api that's to be used to get access to the calendar api, https://apis.google.com/js/api.js, you can see that the variable, gapi is defined on the first line right there.

![image](https://user-images.githubusercontent.com/21962421/77219127-d1ee3a00-6aef-11ea-9e6d-76a4d523e583.png)

With a clean vanilla HTML, I was able to console.log the gapi variable. (The function there is what you feed a discoveryDoc to, to get the right api for whatever... https://youtu.be/Bj15-6rBHQw?t=324 )

![image](https://user-images.githubusercontent.com/21962421/77219164-49bc6480-6af0-11ea-82de-0bf3b79e4366.png)

However, doing the same in Svelte only results in errors. 

![image](https://user-images.githubusercontent.com/21962421/77219194-943de100-6af0-11ea-9a2c-92f7d3873120.png)

This is puzzling, since you can see that gapi exists in the source code, within bundle.js. But there's no var gapi!

![image](https://user-images.githubusercontent.com/21962421/77219206-bf283500-6af0-11ea-9ed0-4fed9d81589b.png)

![image](https://user-images.githubusercontent.com/21962421/77219381-92751d00-6af2-11ea-8460-3d189726fef6.png)

My current best guess on what's going on here is that Svelte+rollup set-up is optimizing the heck out of even external js files while making the bundle.js. It's changing the gapi variable's name to something like... `var gapi` becomes `var a`, to further reduce the file size.

If this is the case, it also explains why I couldn't find any way to access ```firebaseConfig``` from src/firebase.js. The variable was also renamed to something else.

It's either that, or I'm being dumb right now. (And yesterday!)

I've been working though the svelte tutorials. When I reach the end, I'll be looking at the rollup docs.

**Comment by Shiroraven** [comment]
Turns out it's very easy to get the 'gapi' variable reference.
adding the script to the head tag of the index.html file like you did in your vanilla example worked like a charm.

**Comment by Shiroraven** [comment]
5a04db3dbf507f45bd1315b3203d0e240509dd7f implemented a quick test of the now working Google Calendar API Client. Thanks for your effort! 🎉 ❤️ 

 Closing #2
